version: '2'
services:
    training09-app:
        image: training09
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://training09-mysql:3306/training09?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://training09-elasticsearch:9200
        ports:
            - 8080:8080
    training09-mysql:
        extends:
            file: mysql.yml
            service: training09-mysql
    training09-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: training09-elasticsearch
